apiVersion: apps/v1
kind: Deployment
metadata:
  name: categories-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: categories-service
  template:
    metadata:
      labels:
        app: categories-service
    spec:
      containers:
      - name: categories-service
        image: chaimshwartz/categories-service:latest
        ports:
        - containerPort: 5003
        env:
        - name: NODE_ENV
          value: "production"
        - name: DB_HOST
          value: "postgres-categories"