apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trips-service
  template:
    metadata:
      labels:
        app: trips-service
    spec:
      containers:
      - name: trips-service
        image: chaimshwartz/trips-service:latest
        ports:
        - containerPort: 5001
        env:
        - name: NODE_ENV
          value: "production"
        - name: DB_HOST
          value: "postgres-trips"