name: Build and Deploy Microservices

on:
  push:
    branches:
      - main  # פועל כשאתה עושה `git push` ל-main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Auth Service
        run: |
          docker build -t chaimshwartz/auth-service:latest ./backend/services/auth
          docker push chaimshwartz/auth-service:latest

      - name: Build and push Trips Service
        run: |
          docker build -t chaimshwartz/trips-service:latest ./backend/services/trips
          docker push chaimshwartz/trips-service:latest

      - name: Build and push Expenses Service
        run: |
          docker build -t chaimshwartz/expenses-service:latest ./backend/services/expenses
          docker push chaimshwartz/expenses-service:latest

      - name: Build and push Users Service
        run: |
          docker build -t chaimshwartz/users-service:latest ./backend/services/users
          docker push chaimshwartz/users-service:latest

      - name: Build and push Categories Service
        run: |
          docker build -t chaimshwartz/categories-service:latest ./backend/services/categories
          docker push chaimshwartz/categories-service:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: latest

      - name: Configure kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/services/auth-service.yaml
          kubectl apply -f k8s/services/trips-service.yaml
          kubectl apply -f k8s/services/expenses-service.yaml
          kubectl apply -f k8s/services/users-service.yaml
          kubectl apply -f k8s/services/categories-service.yaml
          kubectl apply -f k8s/ingress.yml
          kubectl apply -f k8s/deployments/auth-deployment.yaml
          kubectl apply -f k8s/deployments/trips-deployment.yaml
          kubectl apply -f k8s/deployments/expenses-deployment.yaml
          kubectl apply -f k8s/deployments/users-deployment.yaml
          kubectl apply -f k8s/deployments/categories-deployment.yaml
